language: node_js

node_js: stable

install:
  - npm install

script:
  - hexo cl
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "yanyx"
  - git config user.email "yixingyan@gmail.com"  
  - git add .
  - git commit -m "update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master  

branches:
  only:
    - source  
env:
 global:
   - GH_REF: github.com/yanyixing/yanyixing.github.io
